### ISSUE TITLE
Two questions about the distance gap

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [UrbComp/DeepTTE#2]
It is a very Nice job! 

Two question:
1. You said that: "The GPS devices usually generate one record for every fixed length time gap ....... To avoid such case, we resample each historical trajectory such that the distance gap between two consecutive points are around 200 to 400 meters."

Additionally, you said that the distance gaps in the testing data are equal.
Are the distance gaps between two consecutive points in the training data equal?  or each distance gap in the training data is different and each one is randomly selected from 200 to 400 meters?

2.  You said that: "During the test phase, to make the testing data consistent
with the training data, we convert a path P to a sequence of
location points with equal distance gaps."

How do you convert the path P to a sequence of location points with equal distance gaps? Could you generously publish the code that achieves the function? You encourage users to User Your Own Data, but we can not use our own data if we don't know how to convert the path P to a  sequence of location points with equal distance gaps.

Thank you for your answer.

**Comment by cloud-waiting-for-wind** [comment]
Thank you for sparing your precious time answering the question.
But how about the second question ( How can I convert the path P in the test data to a sequence of location points with equal distance gaps) ?

**Comment by caow13** [comment]
@cloud-waiting-for-wind 
It depends on your input format.
In our experiment, a path P in test data is also a sequence of location points (without timestamp) like that in the training set. If your test data is a sequence of road segments, you can first uniformly draw many points in each road and then use the above scripts.

**Comment by cloud-waiting-for-wind** [comment]
Thank you very much for your patiently explaining.
In fact, my data is also a sequence of location points (no matter training data or testing data). But each points is record with equal time interval (30 seconds), so each gap between two consecutive points is different.
In my opinion, if I want to convert a path with fixed length time gap to a path with fixed length distance gap, I may need to:
1. Fitting a curve for each path according to the  fixed length time gap points.
2. Equidistant sampling in the fitted curve to obtain fixed distance gap.

But I think it very complex and time-consuming to fitting a curve for each path.  So could you generously publish the code that achieves the function? or you use a simpler method to finish this work?

**Comment by caow13** [comment]
@cloud-waiting-for-wind 
No, actually you do not need to fit a curve. The pseudo code above is enough.
What you need are only two steps:
1. select the first location point into a list L
2. check if the distance of the current point and L[-1] is between [200, 400]; if so, add it into L; otherwise, step to the next location point.

You do not need make the distance gaps strictly equal. The randomness of distance gaps can be handled by the model.

**Comment by cloud-waiting-for-wind** [comment]
I get it.
Thank you for you reply!
